### ISSUE TITLE
"Island out of bounds"

### ISSUE THREAD

**Issue by unfa** [muhuk/grid-uv-packer#2]
I've tested version 1.0 on a simple model and I got this error:
![image](https://user-images.githubusercontent.com/491704/220424580-c9c80a34-0c94-444c-8f03-dffa0080dda6.png)
I tried a different unwrap and managed to get it to not happen, but I don't know if this is a bug in the plug-in on my error?
This is in Blender 3.4.1 on Windows 10.

**Comment by unfa** [comment]
So the unwrap above was achieved by "Smart UV Project" function. Once I added some seams and did an Unwrap, it no longer errors out, but still fails to affect the UVs in any way:

![image](https://user-images.githubusercontent.com/491704/220426831-dec1433e-b939-4e20-b0b6-aefcc47d6bb0.png)

I first did a standard pack and then tried using Grid Packer - but it didn't do anything.
I'll test on Linux too, I suspect it will work there.

**Comment by muhuk** [comment]
The way unwrapping was done (`Unwrap` or `Smart UV Project` or `Reset UV`) does not matter. Only thing that matters is islands to be packed need to be selected (same as built-in pack command).

That error was removed in `v1.0`, it seems to me your Blender is still using an earlier version.

**Comment by unfa** [comment]
Hmm. That'd explain why it doesn't seem to work at all. I'll wipe it and make sure the newest version is installed. Thanks!

**Comment by muhuk** [comment]
Closing this one.
